sudo: false
language: python
python:
  - "2.7"
  - "pypy"
install: pip install coverage python-coveralls tox
script: tox -e coverage
after_success: coveralls
matrix:
  allow_failures:
    - python: "pypy"
