language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
install:
  - pip install twisted pyOpenSSL pyflakes coverage python-coveralls
script:
  - make pyflakes
  - python setup.py build
  - coverage run `which trial` foolscap
after_success:
  - coveralls
